
name: Run Email Bot Optimized

on:
#  schedule:
 #   - cron: '*/8 * * * *'  # כל 5 דקות
  workflow_dispatch:        # כפתור הפעלה ידנית

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # התיקון הקריטי: שינוי מ-v2 ל-v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # עכשיו זה יעבוד!

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot script
        env: 
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python python_bot.py
